"""initial

Revision ID: 02a162e07b6b
Revises: 
Create Date: 2026-08-11 04:59:34.357110
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '02a162e07b6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('perfil_id', sa.Uuid(), nullable=False),
    sa.Column('task_num', sa.SmallInteger(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_perfil_id'), 'eventos', ['perfil_id'], unique=False)
    op.create_table('perfiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('es_nino', sa.Boolean(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('idioma_materno', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('profesion', sa.String(), nullable=True),
    sa.Column('centro', sa.String(), nullable=True),
    sa.Column('colegiado', sa.String(), nullable=True),
    sa.Column('relacion', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('codigos_vinculacion',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('perfil_id', sa.Uuid(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('tutores_perfil',
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('perfil_id', sa.Uuid(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tutor_id', 'perfil_id')
    )
    op.create_table('vinculos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profesional_id', sa.Uuid(), nullable=False),
    sa.Column('perfil_id', sa.Uuid(), nullable=False),
    sa.Column('via', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profesional_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profesional_id', 'perfil_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vinculos')
    op.drop_table('tutores_perfil')
    op.drop_table('refresh_tokens')
    op.drop_table('codigos_vinculacion')
    op.drop_table('usuarios')
    op.drop_table('perfiles')
    op.drop_index(op.f('ix_eventos_perfil_id'), table_name='eventos')
    op.drop_table('eventos')
    # ### end Alembic commands ###
